Repository Qodat/qodat, pull requests merged in 2022-08, with the labels that each got.

#1 Use Java 17 when building qodat-api
  build.gradle.kts
  qodat-api/build.gradle.kts
Labels: maintenance

#3 Add GitHub Workflow to create distributions for Windows, Linux, and Mac
  .github/workflows/gradle-build.yaml
Labels: maintenance

#4 Add workflow_dispatch trigger so we can manually run this workflow
  .github/workflows/gradle-build.yaml
Labels: maintenance

#5 Remove JitPack repo
  build.gradle.kts
Labels: maintenance

#7 Add GitHub issue templates
  .github/ISSUE_TEMPLATE/bug-report.md
  .github/ISSUE_TEMPLATE/feature-request.md
Labels: documentation

#6 Cleaned up project structure and updated deps
  build.gradle.kts
  qodat-api/build.gradle.kts
Labels: maintenance

#8 Made selected animation move to top of animation tree
  src/main/kotlin/stan/qodat/scene/control/tree/EntityTreeItem.kt
Labels: enhancement
